# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89291a801637a054c6b3d38aed3020624808563bca322423ddaf182e33c2a40656507efa5beeb4fdc71c722fad99913455c2fa33507b1094fc444794c10d661b

test:
  secret_key_base: a07d622777b07863525a1c3d7574b678026d9dd13c7a4708e2080c0b9bb3b80d5f103ad9a803f1d975c206426a2f91fefecb2b1b825a11a777a2a1dadd892da4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
